collector:
  interval: 5m
  timeout: 5s
  retries: 2
  retry_delay: 2s

database:
  path: ./data/ipwatcher.db

logging:
  level: info

providers:
  - https://api.ipify.org
  - https://ipv4.icanhazip.com
  - https://4.ident.me
